---
title: Especialidade de Programação
author: admin
date: '2021-03-19'
slug: especialidade-de-programação
categories:
  - programação
  - R
  - RMarkdown
tags:
  - Teste
  - Tutoriais
  - Especialidades
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-19T23:53:52-03:00'
featured: no
image:
  caption: ''s
  focal_point: ''
  preview_only: no
projects: []
---

# A especialidade de Programação:

Vamos neste post aprender mais sobre a especialidade de programação.

## **Os itens da especialidade:**

1. Explicar como programas de computador e aplicativos podem facilitar tarefas do dia a dia.

2. Mostrar conhecimento sobre os fundamentos básicos da programação e o uso das cláusulas IF (se) e WHILE (enquanto), através de 1 (um) pequeno código funcional.

3. Escolher uma linguagem de programação e identificar quais os recursos mínimos, de hardware e software, são necessários para colocar 1 (um) programa em funcionamento.

4. Desenvolver 1 (um) programa que ao ser executado apresente na tela os dizeres “Alô Mundo”.

5. Realizar uma apresentação sobre o que é software livre, citando exemplos.

6. Citar pelo menos 3 (três) tipos de licenciamento de programas e explicar como a pirataria pode ser prejudicial.

7. Desenvolver 1 (um) jogo ou aplicativo em qualquer linguagem ou 1 (um) site que utilize programação JavaScript ou equivalente com uma função relacionada ao escotismo. Após, apresentá-lo para a sua seção.

8. Explicar o uso de pelo menos 5 (cinco) funções em uma linguagem de programação bem como em que local pode-se buscar referências.

9. Citar 3 (três) repositórios de código e mostrar como podem agilizar a programação de software.

10. Demonstrar conhecimentos básicos sobre pelo menos 1 (um) ambiente de desenvolvimento integrado mostrando conhecimento quanto a sua utilização.

11. Pesquisar como funciona uma empresa de jogos digitais e relatar o seu funcionamento ao examinador.

12. Apresentar uma pesquisa sobre o que são emuladores.