---
title: Sobre o Projeto
author: admin
date: '2021-03-18'
slug: sobre-o-projeto
categories:
  - Apresentação
tags:
  - Projeto
  - Coding
  - Escotismo
  - B-P
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-20T00:06:24-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# O que é o Projeto Coding?

O Projeto Coding é parte do projeto de relevância para a Insígnia de B-P do pioneiro Caio Gomes Alves (este que vos escreve). Ele tem como objetivo auxiliar na integração de programação no Movimento Escoteiro.

# Motivo do Projeto:

A principal motivação por trás da ideia é mostrar diferentes prospectivas que podem ser aplicadas ao Movimento Escoteiro através da programação. Além disso, devido ao momento adverso causado pela pandemia de COVID-19 nos anos 2020 e 2021, levando à transição das atividades escoteiras para a esfera digital, é uma ótima oportunidade de desenvolver uma nova habilidade nos Jovens e Adultos escoteiros.

# Como o Projeto será desenvolvido?

O desenvolvimento será por meio deste site, a partir de postagens periódicas de dicas, tutoriais e sugestões de aplicações da programação nas diversas atividades escoteiras.

# Público-alvo:

O público-alvo deste projeto são Jovens (Escoteiros, Sêniores e Pioneiros) e Adultos interessados em desenvolver suas habilidades em programação e aplicá-las no Movimento Escoteiro, seja pelo desejo de adquirir uma especialidade para a Progressão pessoal (como a especialidade de Programação, por exemplo), seja pela possibilidade de aplicar uma atividade com os Jovens desenvolvendo um código de programação ou um jogo envolvendo escotismo.

Apesar disso, o site será público, disponibilizando os seus conteúdos para a comunidade geral, não apenas escoteiros. Desta forma, busca-se ampliar o número de leitores, e consequentemente ampliar o número de beneficiados, uma vez que o conhecimento deve ser compartilhado pelo maior número de pessoas possível.

# Divulgação:

A divulgação deste projeto será feita por meio das redes sociais, tanto pelo Instagram próprio, quanto pelas redes sociais do autor e do Clã Pioneiro Agathon (quando possível).

Além disso, o autor buscará entrar em contato com outros Grupos Escoteiros com o propósito de divulgar o projeto, bem como a possibilidade de dar workshops e cursos para os Jovens desses grupos contatados.

# Avaliação:

A avaliação deste projeto será feita aproximadamente 6 meses após o início das postagens, e será feita através de formulário a ser desenvolvido e analisado posteriormente.

O formulário será destinado aos leitores do site, que responderão questões sobre a relevância, qualidade e recepção geral das postagens deste projeto.